# @name get-prompts
GET http://localhost:3333/prompts

###

# @name uplaod
POST  http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebkitFormBoundary7MA4YWxkTrZu0gW

------WebkitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebkitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/a9253028-406c-4e3c-8c51-43633dff9f2d/transcription
Content-Type: application/json

{
  "prompt": "tailwindcss, eslint, next"
}

###

# @name generate-ai-complettion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "a9253028-406c-4e3c-8c51-43633dff9f2d",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do video informado a seguir: '''{transcription}'''"
}
